=== Table story_comments

The story_comments table stores information about comments made by story seekers on stories.

[cols="3*"]
|===
^| Column Name ^| Data Type ^| Constraints
| id | INT | PRIMARY KEY, AUTO_INCREMENT
| story_id | INT | NOT NULL, FOREIGN KEY (story_id) REFERENCES stories(id) ON DELETE CASCADE
| user_id | INT | NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
| comment TEXT | NOT NULL
| created_at | TIMESTAMP | DEFAULT NOW()
| updated_at | TIMESTAMP | DEFAULT NOW() ON UPDATE NOW()
|===

* The id column is an auto-incrementing integer that serves as the primary key of the table.
* The story_id column is a non-null integer that references the id column in the stories table and specifies the story that the comment is for. If a story is deleted from the stories table, then all corresponding comments will be automatically deleted from the story_comments table due to the ON DELETE CASCADE constraint.
* The user_id column is a non-null integer that references the id column in the users table and specifies the story seeker who made the comment. If a user is deleted from the users table, then all corresponding comments will be automatically deleted from the story_comments table due to the ON DELETE CASCADE constraint.
* The comment column is a non-null text field that specifies the comment made by the story seeker.