version: '3.8'
services:
 web:
  image: josephemeka/folklore-app:1.0
  ports: 
   - "81:80"
  volumes: 
   - .:/var/www/html
  
 db:
  image: mysql:8.1
  container_name: my_docker_sql
  volumes:
   - ./db_data:/var/lib/mysql
   - ./folktales_backup.sql:/docker-entrypoint-initdb.d/folktales_backup.sql
  environment:
   MYSQL_ROOT_PASSWORD: tiger
   MYSQL_DATABASE: folktales
  #  MYSQL_USER: root
  ports: 
   - "3306:3306"
  

# $servername = "lamp-mysql8";
# $dbname = 'folktales'; 
# $username = 'root';
# $password = 'tiger';